# jail.conf for container: demo1
# Included by the default recipes/jail.conf.
# Shared defaults (exec.start, mount.devfs, etc.) are inherited.
# See jail.conf(5) for options.

demo1 {
    host.hostname = "demo1";
    path = "/containers/demo1";
    mount.fstab = "/compat/linux/root/parasa/recipes/containers/demo1/mount.fstab";
}
